# Generated by Django 4.1 on 2024-10-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0006_news_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="view_count",
        ),
    ]
